name = "htmlchat"
main = "src/index.js"
compatibility_date = "2025-08-07"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]